import ollama

MODEL = "qwen2.5:3b"


def clean_sql(sql: str) -> str:
    """
    Clean SQL generated by the LLM.
    """

    sql = sql.replace("```sql", "")
    sql = sql.replace("```", "")
    sql = sql.replace("SQL", "")
    sql = sql.strip()

    if ";" not in sql:
        sql += ";"

    return sql


def validate_generated_sql(sql: str) -> bool:
    """
    Basic validation to ensure only safe SELECT queries are executed.
    """

    sql_lower = sql.lower().strip()

    blocked_keywords = [
        "drop",
        "delete",
        "update",
        "insert",
        "alter",
        "truncate",
        "create",
        "replace",
        "attach",
        "detach",
        "pragma",
    ]

    if not sql_lower.startswith("select"):
        return False

    for keyword in blocked_keywords:
        if keyword in sql_lower:
            return False

    return True


def generate_sql(question: str, schema: str) -> str:
    """
    Convert a natural language question into SQLite SQL.
    """

    prompt = f"""
You are an expert SQLite SQL developer.

Your task is to convert natural language into SQL.

DATABASE SCHEMA

{schema}

RULES

1. Return ONLY SQL.
2. Do NOT explain anything.
3. Do NOT use markdown.
4. Do NOT use ``` blocks.
5. Use ONLY the tables and columns listed in the schema.
6. Generate ONLY SELECT queries.
7. Never generate DROP, DELETE, UPDATE, INSERT, ALTER, CREATE, PRAGMA or TRUNCATE.
8. SQL must be compatible with SQLite.
9. End the query with a semicolon.

Question:
{question}
"""

    try:

        response = ollama.chat(
            model=MODEL,
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        sql = response["message"]["content"]

        sql = clean_sql(sql)

        if not validate_generated_sql(sql):
            raise Exception("Unsafe SQL generated by AI.")

        return sql

    except Exception as e:
        raise Exception(f"AI SQL Generation Failed: {e}")