import streamlit as st
import google.generativeai as genai

# Configure Gemini
genai.configure(api_key=st.secrets["GEMINI_API_KEY"])

MODEL = genai.GenerativeModel("gemini-2.5-flash")


def clean_sql(sql: str) -> str:
    """
    Clean SQL generated by the LLM.
    """

    sql = sql.replace("```sql", "")
    sql = sql.replace("```", "")
    sql = sql.replace("SQL", "")
    sql = sql.strip()

    if ";" not in sql:
        sql += ";"

    return sql


def validate_generated_sql(sql: str) -> bool:
    """
    Ensure only safe SELECT queries are executed.
    """

    sql_lower = sql.lower().strip()

    blocked_keywords = [
        "drop",
        "delete",
        "update",
        "insert",
        "alter",
        "truncate",
        "create",
        "replace",
        "attach",
        "detach",
        "pragma",
    ]

    if not sql_lower.startswith("select"):
        return False

    for keyword in blocked_keywords:
        if keyword in sql_lower:
            return False

    return True


def generate_sql(question: str, schema: str) -> str:
    """
    Convert natural language into SQLite SQL.
    """

    prompt = f"""
You are an expert SQLite SQL developer.

Your task is to convert natural language into SQL.

DATABASE

Table Name:
data

Schema:
{schema}

RULES

1. Return ONLY SQL.
2. Do NOT explain anything.
3. Do NOT use markdown.
4. Do NOT use ``` blocks.
5. Use ONLY the table named data.
6. Use ONLY the columns listed in the schema.
7. Generate ONLY SELECT queries.
8. Never generate DROP, DELETE, UPDATE, INSERT, ALTER, CREATE, PRAGMA or TRUNCATE.
9. SQL must be compatible with SQLite.
10. End the query with a semicolon.

Question:
{question}
"""

    try:

        response = MODEL.generate_content(prompt)

        sql = response.text

        sql = clean_sql(sql)

        if not validate_generated_sql(sql):
            raise Exception("Unsafe SQL generated by AI.")

        return sql

    except Exception as e:
        raise Exception(f"AI SQL Generation Failed: {e}")